apiVersion: v1
kind: Service
metadata:
  name: hystrix-producer
  labels:
    app: hystrix-producer
spec:
  type: LoadBalancer
  ports:
  - port: 7070
    targetPort: 7070
  selector:
    app: hystrix-producer
