apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hystrix-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hystrix-producer
    spec:
      containers:
      - name: hystrix-producer
        image: diegopacheco/hystrixprod
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 8080
