version: "3"
services:
  microservice:
    image: packt/microservice
    networks:
        default:
          ipv4_address:  172.10.0.70
    links:
      - redis
      - eureka
      - hystrixdash
  redis:
    image: redis
  eureka:
    image: packt/eureka
    networks:
        default:
          ipv4_address:  172.10.0.55
  hystrixdash:
    image: packt/hystrixdash

networks:
    default:
        external:
            name: packtNet
